logging:
    file:
        name: logs/sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Abcd1234!
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: choiyj
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: chlvldzmf96@gmail.com
        password: lwjktvvbqhhhauym
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        auth-code-expiration-millis: 1800000

    servlet:
      multipart:
          location: uploads/
          max-file-size: 10MB
    thymeleaf:
        prefix: classpath:/templates
    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        user-name-attribute: id
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
                registration:
                    kakao:
                        client-name: kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/kakao
                        client-id: c638d6ed837b95704939be5e10787d49
                        client-secret: 82MfOIBInRdpJDd4yLnWBT0HuGtgppDx
                        client-authentication-method: client_secret_post
                        scope: account_email, profile_nickname, profile_image
                    google:
                        client-id: 518438414773-vqjasgbp2us0a1pv7opsck8ckudjbp16.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/google
                        scope:
                            - email
                            - profile

# 파일 업로드 설정
file:
    upload:
        path: uploads/

