logging:
    file:
        name: logs/sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info
server:
    port: 8080
    servlet:
        context-path: /oauthTest
spring:
    application:
        name: oauthTest
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Abcd1234!
        url: jdbc:mysql://127.0.0.1:3306/studydb
        username: choiyj
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    thymeleaf:
        prefix: classpath:/templates

    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        user-name-attribute: id
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
                registration:
                    kakao:
                        client-name: kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/oauthTest/login/oauth2/code/kakao
                        client-id: c0e1429b0bf3900823555741e46cf575
                        client-secret: crZMSgNpXerE9FmFJmHxIeDmoIn7nKGa
                        client-authentication-method: client_secret_post
                        scope: profile_nickname, profile_image
                    google:
                        client-id: 518438414773-fhu5m2vlufjo7fbtk46m6rvd7glq64jo.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/oauthTest/login/oauth2/code/google
                        scope:
                            - email
                            - profile
